version: '3.6'

services:

  app:
    ports:
      - "443:443"
    volumes:
      - ./front/dist:/app/dist
    environment:
      - APPLICATION_SECRET_GITHUB_TOKEN=foo
      - APPLICATION_SECRET_ADMIN=abcdefghijklmnopqrstuvwxyz123456

  front-watcher:
    build: 
      context: .
      target: front-watcher
    volumes:
      - ./front/dist:/app/dist
      - ./front/src:/app/src
